Few commands added
crescentpartha/CheatSheets-for-Developers pull request #112
Opened 2022-10-21 18:23 UTC by dotsbeauty

### What does this PR do?
> Add content(s) | Add new CheatSheet | Add new feature

### Description
> Added new HTML commands which are valid in HTML5 and some in CSS

### Screenshots or Links
> If applicable, add `screenshots` or a modified `UI link` to help understand your contribution.

### Additional context
> Wanted to add more but format gets disturbed. You could help me to add few more.

### Checklist:
- [x] Read our [contributing guidelines](../docs/CONTRIBUTING.md).
- [ x] Search for duplicates.
- [x] Used an informative name for this pull request.

### Follow-up
- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-21 18:39 UTC, crescentpartha requested changes
Please, modify based on the requirements.

2022-10-21 18:39 UTC, crescentpartha commented on CheatSheets/html-cheatsheet.md
> +**[🔼Back to Top](#table-of-contents)**
Those lines of code `break the table format`.
- Double `Graphics header`
- Double `canvas` added

2022-10-21 18:39 UTC, crescentpartha commented on CheatSheets/html-cheatsheet.md
> +| `<code> ... </code>`             | Defines sample output from a computer program                                               |
Already exist.

2022-10-22 04:43 UTC, dotsbeauty reviewed
Conflict resolved

2022-10-22 11:41 UTC, crescentpartha requested changes
Please, modify the broken tables.

2022-10-22 11:41 UTC, crescentpartha commented on CheatSheets/html-cheatsheet.md
> +**[🔼Back to Top](#table-of-contents)**
```suggestion
## Graphics

| Command                    | Description                                                        |
| --------------------- | ------------------- |
| `<canvas> … </canvas>`     | Used to draw graphics on a web page using javascript.    |
| `<svg> … </svg>`           | Used to defines vector-based graphics in XML format.               |

**[🔼Back to Top](#table-of-contents)**

## Media

| Command                    | Description                                      |
| --------------------- | ------------------- |
| `<video> … </video>`       | Used to show a video on a web page.              |
| `<audio> … </audio>`       | Used to play an audio file on a web page.        |

**[🔼Back to Top](#table-of-contents)**
```
The table is broken again. [here](https://github.com/dotsbeauty/CheatSheets-for-Developers/blob/main/CheatSheets/html-cheatsheet.md#graphics)

2022-10-22 11:42 UTC, crescentpartha approved these changes
Approved.

2022-10-22 11:42 UTC, merged