Update html-cheatsheet.md
crescentpartha/CheatSheets-for-Developers pull request #153
Opened 2022-10-23 05:17 UTC by ritwikdalmia

### What does this PR do?
> Updated HTML cheatsheets with form tag

2022-10-23 05:54 UTC, crescentpartha requested changes
Please, modify your codes.

2022-10-23 05:54 UTC, crescentpartha commented on CheatSheets/html-cheatsheet.md
> +| submit button | `<input type="submit">`  | activates the form's submission <br/>(a `POST` request or <br/>Javascript action) |
Table format is broken [here](https://github.com/ritwikdalmia/CheatSheets-for-Developers/blob/ritwikdalmia-html-cheetsheet/CheatSheets/html-cheatsheet.md#input-types)

2022-10-23 05:54 UTC, crescentpartha commented on CheatSheets/html-cheatsheet.md
> +**[🔼Back to Top](#table-of-contents)**
```suggestion
```
Please, follow the tabular format. You didn't follow the [contributing guidelines](https://github.com/crescentpartha/CheatSheets-for-Developers/blob/main/docs/CONTRIBUTING.md).
This is a CheatSheet, not an elaborate tutorial. Use `one row` in a table for a `single tag`.
| Command | Description |
| -------- | ---------------- |
| `<label> ... </label>` | Define a label for an HTML form widget |

2022-10-23 05:54 UTC, crescentpartha commented on CheatSheets/html-cheatsheet.md
> +  - [The `<label>` Element (Tag)](#The-label-Element)
Don't create unnecessary Headings.

2022-10-23 05:54 UTC, crescentpartha commented on CheatSheets/html-cheatsheet.md
> +## INPUT Types
```suggestion
```
This section will be quite useful if you keep it simple, meaningful, and readable. Please, maintain the `tabular format`.

2022-10-23 06:15 UTC, ritwikdalmia commented
i have resolve all the conflict please check once again

2022-10-23 19:36 UTC, ritwikdalmia commented
please merge this PR

2022-10-24 19:30 UTC, crescentpartha approved these changes
Approved.

2022-10-24 19:30 UTC, merged