Update cpp-stl-cheatsheet.md with pair sorting
crescentpartha/CheatSheets-for-Developers pull request #158
Opened 2022-10-23 06:32 UTC by LegendaryGene

### What does this PR do?
> Add content(s) 

### Description
> Added sorting by first and second element in cpp pair

### Additional context
>Uses internal quicksort implementation for sorting

### Checklist:
- [x] Read our [contributing guidelines](../docs/CONTRIBUTING.md).
- [x] Search for duplicates.
- [x] Used an informative name for this pull request.

### Follow-up
- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-23 19:14 UTC, LegendaryGene commented
Please Merge this so I can get the HacktoberFest submission @crescentpartha

2022-10-23 20:14 UTC, crescentpartha requested changes
Request changes.

2022-10-23 20:14 UTC, crescentpartha commented on CheatSheets/cpp-stl-cheatsheet.md
>  **[🔼Back to Top](#table-of-contents)**
```suggestion
```
Remove this line from the block code and then add the **[🔼Back to Top](#table-of-contents)** below the block code.

2022-10-24 09:17 UTC, LegendaryGene commented
Done, now please do @crescentpartha

2022-10-24 18:36 UTC, crescentpartha approved these changes
Approved.

2022-10-24 18:36 UTC, merged