add 3 array methods in javascript cheatsheet
crescentpartha/CheatSheets-for-Developers pull request #166
Opened 2022-10-23 14:07 UTC by MaxR522

### What does this PR do?
> Add contents

### Description
> Add 3 array methods in javascript cheatsheet

### Screenshots or Links
> If applicable, add `screenshots` or a modified `UI link` to help understand your contribution.

### Additional context
> Add any other context about your PR.

### Checklist:
- [x] Read our [contributing guidelines](../docs/CONTRIBUTING.md).
- [x] Search for duplicates.
- [x] Used an informative name for this pull request.

### Follow-up
- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-23 19:28 UTC, crescentpartha requested changes
Please, modify your code or answer my question.

2022-10-23 19:28 UTC, crescentpartha commented on CheatSheets/JavaScript-CheatSheet.md
> -| valueOf()     | Returns the primitive value of the specified object                     |
You deleted the `valueOf()` column. Please, add this line or tell me why you deleted it.

2022-10-24 05:51 UTC, MaxR522 commented
> Please, modify your code or answer my question.

Sorry!!
My bad, I will modify it

2022-10-24 12:48 UTC, MaxR522 commented
I fixed it in this commit [cfce718](https://github.com/crescentpartha/CheatSheets-for-Developers/pull/166/commits/cfce71892e44cebe77a510ed42b2f6a90ae8a9f1)

2022-10-24 18:20 UTC, crescentpartha approved these changes
Approved your changes.

2022-10-24 18:21 UTC, merged