Update pandas-cheatsheet.md
crescentpartha/CheatSheets-for-Developers pull request #201
Opened 2022-10-25 14:06 UTC by ritwikdalmia

### What does this PR do?
> added data visualization with pandas(data frame)

2022-10-25 16:31 UTC, crescentpartha reviewed
Please, give the reference related to this, I didn't find any documentation related to this.

2022-10-25 16:41 UTC, ritwikdalmia commented
https://pandas.pydata.org/docs/user_guide/visualization.html  

this all the details has been taken from here i have precise the data from studying here

2022-10-26 06:04 UTC, crescentpartha requested changes
Please, follow the requirements and modify the codes.

2022-10-26 06:04 UTC, crescentpartha commented on CheatSheets/pandas-cheatsheet.md
> +  - [Data Visualization with dataframe](#Data-Visualization-with-dataframe)
So, you actually defined the `terminology and definitions` in this section.

- Data Visualization with Dataframe
    - Terminology and Definitions

Please, add all of your codes under the `Terminology and Definitions` section in this way.

2022-10-26 07:45 UTC, ritwikdalmia commented on CheatSheets/pandas-cheatsheet.md
> +|**king:str**|
actually it a type of plot like line plot bar plot histogram and all above parameters are same for each type of plot

2022-10-26 07:53 UTC, ritwikdalmia commented
resolved all the conflicts

2022-10-26 09:38 UTC, crescentpartha approved these changes
Approved

2022-10-26 09:38 UTC, merged