Update windows-cheatsheet.md
crescentpartha/CheatSheets-for-Developers pull request #218
Opened 2022-10-28 13:42 UTC by vinay4563

added windows shortcut key

### What does this PR do?
> Add content

2022-10-28 14:43 UTC, tushar-kumar approved these changes
Approved

2022-10-28 14:55 UTC, crescentpartha requested changes
Please, modify your code.

2022-10-28 14:55 UTC, crescentpartha commented on CheatSheets/windows-cheatsheet.md
> +| `Win + Alt + R` | to start in-built screen recording |
```suggestion
| `Win + Alt + R` | Allows you to instantly start or stop recording your screen |
```

2022-10-29 19:58 UTC, crescentpartha approved these changes
Approved but have to modify the code by myself.

2022-10-29 19:58 UTC, merged