Added the npx configure-react commands that help setup react app faster
crescentpartha/CheatSheets-for-Developers pull request #220
Opened 2022-10-28 13:58 UTC by shaantanu9

### What does this PR do?

Added the `npx configure-react` commands that help setup react app faster

### Description
Added the npx configure-react commands that help setup react app faster
https://www.npmjs.com/package/configure-react

### Screenshots or Links

![npx configure-react](https://blogger.googleusercontent.com/img/a/AVvXsEhREIyag4JD3i7vhDplLJcuUq43kNLtlmSgxW1Yd2ltFa9BP78FchqtEiruFpYwyjPUH9AXKClHZjuLAaVlhW4EjlxTew92aihrNZLrBiB0hkdL18k1ok0bB2UKh8NShn8t1ApVF50bXc_yEcK9dZlHoZF0EPQLn2HRsTj1T7O7-Q9xrGCLn9qngY6vhw)

### Additional context
This help any new developer to set the React App Faster and can start learning and implementing things easily

### Checklist:
- [x] Read our [contributing guidelines](../docs/CONTRIBUTING.md).
- [x] Search for duplicates.
- [x] Used an informative name for this pull request.

### Follow-up
- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-28 16:04 UTC, crescentpartha requested changes
Require some modifications. @shaantanu9

2022-10-29 07:07 UTC, shaantanu9 commented on CheatSheets/configure-react-cheatsheet.md
> +| `npx configure-react axios . ` | Install axios and create a folder named `api` and create a file named `axios.js` login.js, register.js, post.js getdata.js |
Yes **. dot is needed** to know that you are in the root folder, similar to git add .

2022-10-29 07:13 UTC, shaantanu9 commented on CheatSheets/npx-cheetsheet.md
> +|`npx sirdeploy github .`| Deploy React App on Github|
This is the ScreenShot of the `npx sirdeploy`

![sirdeploy](https://blogger.googleusercontent.com/img/a/AVvXsEiokHu_HZkgTu3UlpWcqvVD2345TUeCsveKMWQ2-sB1deOyy-ncdRpTGpd07tXmslrNQTJl7hT1ypHt9KzSBbDbkkQ1ndLGgD8CbeZVXrGpUVYdI7lIdM-Wxhr-dopp2MOAC2fB8TSVRlqkRAblTjBbHBfDeUAUQexAzXFFn1AAln7MjB9l7YsncdVB6g)

And this is the Package Link;-  https://www.npmjs.com/package/sirdeploy

2022-10-29 07:15 UTC, shaantanu9 commented on CheatSheets/npx-cheetsheet.md
> +|`npx sirdeploy github .`| Deploy React App on Github|
sorry, its `npx sirdeploy reactapp` to deploy react app on github will correct in the next commit,

This is the Video of the same https://www.youtube.com/watch?v=fybRnR-fSCk

2022-10-29 07:18 UTC, shaantanu9 commented on CheatSheets/configure-react-cheatsheet.md
> +## Create React Cluster App (Multiple React App in One Project) Build new React App in Second
Correcting this, but the Above section commands can be used in any already build react-app not specifically for cluster app, and that is why to know the root where package.json is present using that.

2022-10-29 07:22 UTC, shaantanu9 commented on CheatSheets/configure-react-cheatsheet.md
> +[React Cluster](https://www.youtube.com/watch?v=2MO1_mCXuds&t=3s)
corrected in latest commit, please check

2022-10-29 07:22 UTC, shaantanu9 commented on CheatSheets/npx-cheetsheet.md
> +|`npx sirdeploy github .`| Deploy React App on Github|
corrected in latest commit, please check

2022-10-29 18:40 UTC, crescentpartha approved these changes
Approved your changes.

2022-10-29 18:41 UTC, merged