Added a new cheatsheet of React Js
crescentpartha/CheatSheets-for-Developers pull request #229
Opened 2022-10-29 04:33 UTC by Rohitsuper69

### What does this PR do?
> Add content(s) | Remove content(s) | Add new CheatSheet | Add new feature | Bug fix

### Description
> here is your description

### Screenshots or Links
> If applicable, add `screenshots` or a modified `UI link` to help understand your contribution.

### Additional context
> Add any other context about your PR.

### Checklist:
- [x] Read our [contributing guidelines](../docs/CONTRIBUTING.md).
- [ ] Search for duplicates.
- [ ] Used an informative name for this pull request.

### Follow-up
- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-29 15:42 UTC, Rohitsuper69 commented
Is this rejected or being reviewed?

2022-10-30 06:08 UTC, Rohitsuper69 commented
Hey are you even checking?

2022-10-30 06:34 UTC, crescentpartha requested changes
Modification Requirements:
1. Rename your file from `reactjs-cheatsheet.md` to `react-cheatsheet.md`
2. Add `Table of Contents`
3. Add `title`, `description`, and `created` in the top of the sheet.
4. Follow the [CheatSheet-Template](https://github.com/crescentpartha/CheatSheets-for-Developers/blob/main/docs/CheatSheet-Template.md)

2022-10-30 06:34 UTC, crescentpartha commented on CheatSheets/reactjs-cheatsheet.md
> +---
```suggestion
--- 
title: "ReactJS Cheatsheet"
description: "..."
created: date
---
```

2022-10-30 06:34 UTC, crescentpartha commented on CheatSheets/reactjs-cheatsheet.md
> +## Create React App
Add `Table of Contents` and link all the headings here.

2022-10-30 06:56 UTC, Rohitsuper69 reviewed
Done changes

2022-10-30 14:14 UTC, crescentpartha approved these changes
Approved your changes.

2022-10-30 14:15 UTC, merged