Add command to delete line (vscode)
crescentpartha/CheatSheets-for-Developers pull request #74
Opened 2022-10-20 16:29 UTC by CiroMeiraLins

Resolves #73

2022-10-20 18:17 UTC, crescentpartha requested changes
Request for changes

2022-10-20 18:17 UTC, crescentpartha commented on CheatSheets/vscode-cheatsheet.md
> +| `Ctrl + Alt + K` | Delete line |
```suggestion
| `Ctrl + Shift + K` | Delete line |
```

2022-10-20 21:19 UTC, crescentpartha requested changes
Please, resolve the required changes.

2022-10-20 21:21 UTC, crescentpartha commented on CheatSheets/vscode-cheatsheet.md
> +| `Ctrl + Alt + K` | Delete line |
```suggestion
| `Ctrl + Shift + K` | Delete line |
```
Please, change this line of code.

2022-10-21 03:48 UTC, shrishti147 commented
To delete a line in vs code :-
On Windows : Shift + Alt + Up/Down.
On Mac : Shift + Option + Up/Down.
On Ubuntu : Ctrl + Shift + Alt + Up/Down.

2022-10-21 06:20 UTC, crescentpartha approved these changes

2022-10-21 06:25 UTC, merged